base_url = "https://devendrn.com/"
compile_sass = true
build_search_index = false

title = "devendrn."
description = "Devendran's portfolio."
author = "devendrn"

[markdown]
highlight_code = false

[extra]
error404_title = "Error 404"
error404_description = "Can't find the page you were looking for..."

header_links = [
    { name = "Projects", url = "projects" },
    { name = "Gallery", url = "gallery" },
]

footer_content = "Copyright &copy; devendrn"
